# Generated by Django 5.1 on 2024-09-02 06:33

import housing.variables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.CharField(choices=housing.variables.HousingType.choices, default=housing.variables.HousingType['H'], max_length=20, verbose_name='Type'),
        ),
    ]
