# Generated by Django 5.1 on 2024-09-02 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
