# Generated by Django 5.1 on 2024-09-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_housing_owner_alter_advert_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housing', to='housing.address'),
        ),
    ]
